var generalRoles = {

    "Tank" : new Rol("Tank"),
    "Damage" : new Rol("Damage"),
    "Support" : new Rol("Support")
}

var secondaryRoles = {

    "MainTank" : new Rol("MainTank"),
    "OffTank" : new Rol("OffTank"),
    "FlexTank" : new Rol("FlexTank"),
    //A FlexTank can work like a MainTank and a OffTank, depends of the choice of the other Tank

    "HitscanDamage" : new Rol("HitscaDamage"),
    "ProjectileDamage" : new Rol("ProjectileDamage"),
    "FlankerDamage" : new Rol("FlankerDamage"),

    "MainSupport" : new Rol("MainSupport"),
    "OffSupport" : new Rol("Off"),
    "FlexSupport" : new Rol("FlexSupport")
    //A FlexSupport can work like a MainSupport and a OffSupport, depends of the choice of the other Support
}

var mapTypes = {
    
    "Assault" : new MapType("Assault", 2),
    "Escort" : new MapType("Escort", 3),
    "Control" : new MapType("Control", 3),
    "Hybrid" : new MapType("Hybrid", 3)
}

var defaultPoints = [];

defaultPoints.push("A");
defaultPoints.push("B");
defaultPoints.push("C");

var mapADC = [];

mapADC.push("Attack");
mapADC.push("Defense");
mapADC.push("Control");

var controlMaps = {
    
    "Busan" : ["Downtown","Sanctuary","MEKA Base"],
    "Ilios" : ["Lighthouse","Well","Ruins"],
    "Lijiang Tower" : ["Night Market","Garden","Control Center"],
    "Nepal" : ["Village","Sanctum","Shrine"],
    "Oasis" : ["City Center","Gardens","University"]
}

var maps = {
    
    "Hanamura" : new Map("Hanamura","Assault"),
    "Horizon Lunar Colony" : new Map("Horizon Lunar Colony","Assault"),
    "Paris" : new Map("Paris","Assault"),
    "Temple of Anubis" : new Map("Temple of Anubis","Assault"),
    "Volskaya Indu stries" : new Map("Volskaya Industries", "Assault"),
    
    "Busan" : new Map("Busan","Control"),
    "Ilios" : new Map("Ilios","Control"),
    "Lijiang Tower" : new Map("Lijiang Tower","Control"),
    "Nepal" : new Map("Nepal","Control"),
    "Oasis" : new Map("Oasis", "Control"),
    
    "Dorado" : new Map("Busan","Escort"),
    "Havana" : new Map("Ilios","Escort"),
    "Junkertown" : new Map("Lijiang Tower","Escort"),
    "Rialto" : new Map("Nepal","Escort"),
    "Route 66" : new Map("Oasis", "Escort"),
    "Watchpoint: Gibraltar" : new Map("Oasis", "Escort"),
    
    "Blizzard World" : new Map("Blizzard World","Hybrid"),
    "Eichenwalde" : new Map("Eichenwalde","Hybrid"),
    "Hollywood" : new Map("Hollywood","Hybrid"),
    "King's Row" : new Map("King's Row","Hybrid"),
    "Numbani" : new Map("Numbani", "Hybrid")
}



var tiers = {
    "MetaBomb" : {"Ana":85,"Ashe":65,"Baptiste":95,"Bastion":55,"Brigitte":65,"D.Va":85,"Doomfist":95,"Genji":75,"Hanzo":95,"Junkrat":75,"Lucio":75,"Mccree":75,"Mei":95,"Mercy":65,"Moira":95,"Orisa":95,"Pharah":75,"Reaper":95,"Reinhardt":85,"Roadhog":75,"Sigma":95,"Soldier: 76":65,"Sombra":85,"Symmetra":55,"Torbjörn":75,"Tracer":75,"Widowmaker":75,"Winston":85,"Wrecking Ball":75,"Zarya":85,"Zenyatta":75},
    "All Ranks" : {"Ana":85,"Ashe":85,"Baptiste":95,"Bastion":55,"Brigitte":85,"D.Va":55,"Doomfist":65,"Genji":75,"Hanzo":95,"Junkrat":75,"Lucio":65,"Mccree":95,"Mei":85,"Mercy":85,"Moira":95,"Orisa":75,"Pharah":65,"Reaper":75,"Reinhardt":95,"Roadhog":65,"Sigma":75,"Soldier: 76":65,"Sombra":55,"Symmetra":75,"Torbjörn":95,"Tracer":55,"Widowmaker":65,"Winston":55,"Wrecking Ball":55,"Zarya":85,"Zenyatta":65},
    "Bronze" : {"Ana":65,"Ashe":65,"Baptiste":75,"Bastion":75,"Brigitte":75,"D.Va":65,"Doomfist":55,"Genji":65,"Hanzo":85,"Junkrat":95,"Lucio":75,"Mccree":75,"Mei":85,"Mercy":85,"Moira":95,"Orisa":95,"Pharah":65,"Reaper":95,"Reinhardt":95,"Roadhog":65,"Sigma":85,"Soldier: 76":75,"Sombra":55,"Symmetra":85,"Torbjörn":95,"Tracer":55,"Widowmaker":55,"Winston":55,"Wrecking Ball":55,"Zarya":85,"Zenyatta":55},
    "Silver" : {"Ana":65,"Ashe":75,"Baptiste":75,"Bastion":55,"Brigitte":75,"D.Va":55,"Doomfist":65,"Genji":75,"Hanzo":85,"Junkrat":95,"Lucio":75,"Mccree":85,"Mei":95,"Mercy":85,"Moira":95,"Orisa":85,"Pharah":65,"Reaper":95,"Reinhardt":95,"Roadhog":65,"Sigma":75,"Soldier: 76":65,"Sombra":55,"Symmetra":85,"Torbjörn":85,"Tracer":55,"Widowmaker":65,"Winston":55,"Wrecking Ball":55,"Zarya":85,"Zenyatta":55},
    "Gold" : {"Ana":75,"Ashe":75,"Baptiste":75,"Bastion":65,"Brigitte":85,"D.Va":55,"Doomfist":65,"Genji":75,"Hanzo":85,"Junkrat":85,"Lucio":75,"Mccree":95,"Mei":85,"Mercy":75,"Moira":95,"Orisa":65,"Pharah":65,"Reaper":95,"Reinhardt":95,"Roadhog":65,"Sigma":75,"Soldier: 76":65,"Sombra":55,"Symmetra":85,"Torbjörn":95,"Tracer":55,"Widowmaker":65,"Winston":55,"Wrecking Ball":55,"Zarya":85,"Zenyatta":55},
    "Platinum" : {"Ana":95,"Ashe":85,"Baptiste":95,"Bastion":55,"Brigitte":85,"D.Va":55,"Doomfist":65,"Genji":85,"Hanzo":95,"Junkrat":75,"Lucio":65,"Mccree":95,"Mei":75,"Mercy":85,"Moira":95,"Orisa":65,"Pharah":65,"Reaper":75,"Reinhardt":95,"Roadhog":65,"Sigma":75,"Soldier: 76":65,"Sombra":55,"Symmetra":75,"Torbjörn":85,"Tracer":55,"Widowmaker":65,"Winston":55,"Wrecking Ball":55,"Zarya":85,"Zenyatta":55},
    "Diamond" : {"Ana":85,"Ashe":85,"Baptiste":95,"Bastion":65,"Brigitte":85,"D.Va":55,"Doomfist":75,"Genji":85,"Hanzo":95,"Junkrat":75,"Lucio":65,"Mccree":85,"Mei":75,"Mercy":65,"Moira":85,"Orisa":75,"Pharah":65,"Reaper":65,"Reinhardt":95,"Roadhog":65,"Sigma":85,"Soldier: 76":65,"Sombra":55,"Symmetra":55,"Torbjörn":95,"Tracer":55,"Widowmaker":75,"Winston":55,"Wrecking Ball":55,"Zarya":95,"Zenyatta":65},
    "Master" : {"Ana":75,"Ashe":85,"Baptiste":95,"Bastion":55,"Brigitte":85,"D.Va":55,"Doomfist":85,"Genji":75,"Hanzo":95,"Junkrat":75,"Lucio":65,"Mccree":85,"Mei":85,"Mercy":55,"Moira":65,"Orisa":95,"Pharah":65,"Reaper":55,"Reinhardt":95,"Roadhog":55,"Sigma":95,"Soldier: 76":85,"Sombra":55,"Symmetra":65,"Torbjörn":65,"Tracer":65,"Widowmaker":75,"Winston":55,"Wrecking Ball":75,"Zarya":85,"Zenyatta":75},
    "Grand Master" : {"Ana":55,"Ashe":95,"Baptiste":95,"Bastion":55,"Brigitte":75,"D.Va":65,"Doomfist":75,"Genji":75,"Hanzo":95,"Junkrat":75,"Lucio":65,"Mccree":55,"Mei":95,"Mercy":65,"Moira":55,"Orisa":95,"Pharah":85,"Reaper":55,"Reinhardt":85,"Roadhog":55,"Sigma":95,"Soldier: 76":65,"Sombra":55,"Symmetra":65,"Torbjörn":75,"Tracer":75,"Widowmaker":85,"Winston":65,"Wrecking Ball":85,"Zarya":75,"Zenyatta":85}
}

var heroMaps = {

    "Ana" : {"Attack":{"Hanamura":{"A":0,"B":10},"Horizon Lunar Colony":{"A":10,"B":10},"Paris":{"A":0,"B":10},"Temple of Anubis":{"A":10,"B":0},"Volskaya Industries":{"A":0,"B":10},"Dorado":{"A":0,"B":10,"C":10},"Junkertow":{"A":10,"B":0,"C":10},"Rialto":{"A":0,"B":0,"C":10},"Route 66":{"A":0,"B":0,"C":10},"Watchpoint Gibraltar":{"A":0,"B":0,"C":10},"Havana":{"A":10,"B":0,"C":10},"Blizzard World":{"A":0,"B":10,"C":10},"Eichenwalde":{"A":0,"B":10,"C":10},"Hollywood":{"A":0,"B":10,"C":10},"Kings Row":{"A":10,"B":0,"C":10},"Numbani":{"A":0,"B":10,"C":0}},"Defense":{"Hanamura":{"A":10,"B":10},"Horizon Lunar Colony":{"A":0,"B":10},"Paris":{"A":10,"B":0},"Temple of Anubis":{"A":10,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":10,"B":10,"C":0},"Junkertow":{"A":10,"B":10,"C":10},"Rialto":{"A":10,"B":0,"C":0},"Route 66":{"A":10,"B":0,"C":10},"Watchpoint Gibraltar":{"A":10,"B":0,"C":10},"Havana":{"A":10,"B":0,"C":10},"Blizzard World":{"A":10,"B":10,"C":0},"Eichenwalde":{"A":0,"B":10,"C":0},"Hollywood":{"A":10,"B":10,"C":10},"Kings Row":{"A":10,"B":0,"C":10},"Numbani":{"A":10,"B":10,"C":10}},"Control":{"Ilios":{"Ruins":10,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":10,"Control Center":0},"Nepal":{"Village":0,"Sanctum":10,"Shrine":0},"Oasis":{"City Center":10,"Gardens":0,"University":0},"Busan":{"Sanctuary":10,"Downtown":10,"MEKA Base":10}}},
    "Ashe" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Baptiste" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Bastion" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Brigitte" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":10,"C":10},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":10,"C":10},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "D.Va" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Doomfist" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":-10,"B":-10},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":10,"B":10,"C":10},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":10,"C":10},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":10,"B":10,"C":10}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":-10,"B":-10},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":10,"B":10,"C":10},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":10,"C":10},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":10,"B":10,"C":10}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Genji" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Hanzo" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Junkrat" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Lucio" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Mccree" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Mei" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Mercy" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Moira" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Orisa" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Pharah" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Reaper" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Reinhardt" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":10,"B":10,"C":10},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":10,"B":10,"C":10},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Roadhog" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":10},"Lijiang":{"Market":0,"Garden":10,"Control Center":0},"Nepal":{"Village":0,"Sanctum":10,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":10},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Sigma" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Soldier: 76" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Sombra" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Symmetra" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Torbjörn" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Tracer" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Widowmaker" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Winston" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Wrecking Ball" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Zarya" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
    "Zenyatta" : {"Attack":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Defense":{"Hanamura":{"A":0,"B":0},"Horizon Lunar Colony":{"A":0,"B":0},"Paris":{"A":0,"B":0},"Temple of Anubis":{"A":0,"B":0},"Volskaya Industries":{"A":0,"B":0},"Dorado":{"A":0,"B":0,"C":0},"Junkertow":{"A":0,"B":0,"C":0},"Rialto":{"A":0,"B":0,"C":0},"Route 66":{"A":0,"B":0,"C":0},"Watchpoint Gibraltar":{"A":0,"B":0,"C":0},"Havana":{"A":0,"B":0,"C":0},"Blizzard World":{"A":0,"B":0,"C":0},"Eichenwalde":{"A":0,"B":0,"C":0},"Hollywood":{"A":0,"B":0,"C":0},"Kings Row":{"A":0,"B":0,"C":0},"Numbani":{"A":0,"B":0,"C":0}},"Control":{"Ilios":{"Ruins":0,"Lighthouse":0,"Well":0},"Lijiang":{"Market":0,"Garden":0,"Control Center":0},"Nepal":{"Village":0,"Sanctum":0,"Shrine":0},"Oasis":{"City Center":0,"Gardens":0,"University":0},"Busan":{"Sanctuary":0,"Downtown":0,"MEKA Base":0}}},
}

var heroADC = {

    "Ana" : {"attack":{"Assault":{"A":0,"B":10},"Escort":{"A":10,"B":10,"C":10}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":10,"B":10,"C":0}},"control":0},
    "Ashe" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Baptiste" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Bastion" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Brigitte" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "D.Va" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Doomfist" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Genji" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Hanzo" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Junkrat" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Lucio" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Mccree" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Mei" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Mercy" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Moira" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Orisa" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Pharah" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Reaper" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Reinhardt" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Roadhog" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Sigma" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Soldier: 76" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Sombra" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Symmetra" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Torbjörn" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Tracer" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Widowmaker" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Winston" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Wrecking Ball" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Zarya" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0},
    "Zenyatta" : {"attack":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"defense":{"Assault":{"A":0,"B":0},"Escort":{"A":0,"B":0,"C":0}},"control":0}
}

var counters = {
    "Ana" : {"Ana":0,"Ashe":10,"Baptiste":-10,"Bastion":10,"Brigitte":0,"D.Va":-10,"Doomfist":-10,"Genji":-10,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":10,"Mei":0,"Mercy":0,"Moira":10,"Orisa":0,"Pharah":10,"Reaper":0,"Reinhardt":0,"Roadhog":10,"Sigma":10,"Soldier: 76":0,"Sombra":-10,"Symmetra":0,"Torbjörn":10,"Tracer":-10,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":10,"Zarya":0,"Zenyatta":10},
    "Ashe" : {"Ana":-10,"Ashe":0,"Baptiste":10,"Bastion":0,"Brigitte":10,"D.Va":-10,"Doomfist":10,"Genji":10,"Hanzo":-20,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":0,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":10,"Reaper":10,"Reinhardt":-10,"Roadhog":0,"Sigma":-10,"Soldier: 76":-10,"Sombra":-10,"Symmetra":10,"Torbjörn":10,"Tracer":10,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":-10,"Zarya":10,"Zenyatta":0},
    "Baptiste" : {"Ana":10,"Ashe":-10,"Baptiste":0,"Bastion":10,"Brigitte":0,"D.Va":10,"Doomfist":-10,"Genji":0,"Hanzo":0,"Junkrat":10,"Lucio":-10,"Mccree":10,"Mei":-10,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":20,"Reaper":0,"Reinhardt":10,"Roadhog":-10,"Sigma":20,"Soldier: 76":-10,"Sombra":-10,"Symmetra":10,"Torbjörn":10,"Tracer":10,"Widowmaker":10,"Winston":0,"Wrecking Ball":-10,"Zarya":10,"Zenyatta":0},
    "Bastion" : {"Ana":-10,"Ashe":0,"Baptiste":-10,"Bastion":0,"Brigitte":10,"D.Va":-10,"Doomfist":10,"Genji":-10,"Hanzo":-20,"Junkrat":-10,"Lucio":10,"Mccree":10,"Mei":-10,"Mercy":10,"Moira":10,"Orisa":-10,"Pharah":10,"Reaper":-10,"Reinhardt":20,"Roadhog":-10,"Sigma":-10,"Soldier: 76":-10,"Sombra":-20,"Symmetra":10,"Torbjörn":-10,"Tracer":-10,"Widowmaker":-10,"Winston":20,"Wrecking Ball":10,"Zarya":10,"Zenyatta":-10},
    "Brigitte" : {"Ana":0,"Ashe":-10,"Baptiste":0,"Bastion":-10,"Brigitte":10,"D.Va":10,"Doomfist":-10,"Genji":20,"Hanzo":0,"Junkrat":-10,"Lucio":10,"Mccree":-10,"Mei":0,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":-20,"Reaper":10,"Reinhardt":-10,"Roadhog":10,"Sigma":-10,"Soldier: 76":0,"Sombra":-10,"Symmetra":10,"Torbjörn":-10,"Tracer":20,"Widowmaker":-10,"Winston":10,"Wrecking Ball":0,"Zarya":-10,"Zenyatta":0},
    "D.Va" : {"Ana":10,"Ashe":10,"Baptiste":-10,"Bastion":10,"Brigitte":-10,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":10,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":-10,"Mercy":0,"Moira":20,"Orisa":0,"Pharah":10,"Reaper":10,"Reinhardt":-10,"Roadhog":10,"Sigma":0,"Soldier: 76":10,"Sombra":-10,"Symmetra":-20,"Torbjörn":10,"Tracer":10,"Widowmaker":10,"Winston":10,"Wrecking Ball":0,"Zarya":-20,"Zenyatta":10},
    "Doomfist" : {"Ana":10,"Ashe":-10,"Baptiste":10,"Bastion":-10,"Brigitte":10,"D.Va":0,"Doomfist":0,"Genji":10,"Hanzo":0,"Junkrat":-10,"Lucio":-10,"Mccree":-20,"Mei":0,"Mercy":0,"Moira":-10,"Orisa":-10,"Pharah":-20,"Reaper":-10,"Reinhardt":10,"Roadhog":-10,"Sigma":20,"Soldier: 76":10,"Sombra":-20,"Symmetra":10,"Torbjörn":0,"Tracer":-10,"Widowmaker":-10,"Winston":10,"Wrecking Ball":0,"Zarya":0,"Zenyatta":10},
    "Genji" : {"Ana":10,"Ashe":-10,"Baptiste":0,"Bastion":10,"Brigitte":-20,"D.Va":0,"Doomfist":-10,"Genji":0,"Hanzo":0,"Junkrat":-10,"Lucio":-10,"Mccree":-10,"Mei":-10,"Mercy":0,"Moira":-10,"Orisa":10,"Pharah":-10,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":-20,"Symmetra":-10,"Torbjörn":-10,"Tracer":0,"Widowmaker":10,"Winston":-10,"Wrecking Ball":-10,"Zarya":-10,"Zenyatta":10},
    "Hanzo" : {"Ana":0,"Ashe":20,"Baptiste":0,"Bastion":20,"Brigitte":0,"D.Va":-10,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":10,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":10,"Reinhardt":0,"Roadhog":-10,"Sigma":0,"Soldier: 76":10,"Sombra":10,"Symmetra":10,"Torbjörn":20,"Tracer":10,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":-10,"Zarya":0,"Zenyatta":-10},
    "Junkrat" : {"Ana":0,"Ashe":-10,"Baptiste":-10,"Bastion":10,"Brigitte":10,"D.Va":-10,"Doomfist":10,"Genji":10,"Hanzo":-10,"Junkrat":0,"Lucio":-10,"Mccree":-10,"Mei":20,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":-20,"Reaper":0,"Reinhardt":0,"Roadhog":-10,"Sigma":0,"Soldier: 76":-10,"Sombra":10,"Symmetra":10,"Torbjörn":0,"Tracer":10,"Widowmaker":-10,"Winston":0,"Wrecking Ball":10,"Zarya":-20,"Zenyatta":-10},
    "Lucio" : {"Ana":-10,"Ashe":0,"Baptiste":10,"Bastion":-10,"Brigitte":-10,"D.Va":0,"Doomfist":10,"Genji":10,"Hanzo":0,"Junkrat":10,"Lucio":0,"Mccree":-10,"Mei":10,"Mercy":0,"Moira":-10,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":-10,"Tracer":10,"Widowmaker":0,"Winston":0,"Wrecking Ball":0,"Zarya":0,"Zenyatta":0},
    "Mccree" : {"Ana":-10,"Ashe":-10,"Baptiste":-10,"Bastion":-10,"Brigitte":0,"D.Va":-10,"Doomfist":20,"Genji":10,"Hanzo":-10,"Junkrat":10,"Lucio":10,"Mccree":10,"Mei":-10,"Mercy":10,"Moira":10,"Orisa":10,"Pharah":10,"Reaper":10,"Reinhardt":0,"Roadhog":-10,"Sigma":-20,"Soldier: 76":-10,"Sombra":10,"Symmetra":0,"Torbjörn":10,"Tracer":10,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":20,"Zarya":-20,"Zenyatta":0},
    "Mei" : {"Ana":0,"Ashe":0,"Baptiste":10,"Bastion":10,"Brigitte":0,"D.Va":10,"Doomfist":0,"Genji":10,"Hanzo":-10,"Junkrat":-20,"Lucio":-10,"Mccree":10,"Mei":0,"Mercy":0,"Moira":10,"Orisa":-10,"Pharah":-10,"Reaper":0,"Reinhardt":20,"Roadhog":10,"Sigma":10,"Soldier: 76":-10,"Sombra":10,"Symmetra":10,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":-10,"Wrecking Ball":20,"Zarya":0,"Zenyatta":-10},
    "Mercy" : {"Ana":0,"Ashe":-10,"Baptiste":-10,"Bastion":-10,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":-10,"Mei":0,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":10,"Reaper":0,"Reinhardt":0,"Roadhog":-10,"Sigma":0,"Soldier: 76":-10,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":-10,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":0,"Zarya":0,"Zenyatta":0},
    "Moira" : {"Ana":-10,"Ashe":0,"Baptiste":0,"Bastion":-10,"Brigitte":0,"D.Va":-20,"Doomfist":10,"Genji":10,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":-10,"Mei":-10,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":0,"Reaper":10,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":-10,"Sombra":10,"Symmetra":10,"Torbjörn":0,"Tracer":10,"Widowmaker":-10,"Winston":0,"Wrecking Ball":0,"Zarya":0,"Zenyatta":0},
    "Orisa" : {"Ana":0,"Ashe":-10,"Baptiste":-10,"Bastion":10,"Brigitte":0,"D.Va":0,"Doomfist":10,"Genji":-10,"Hanzo":-10,"Junkrat":-10,"Lucio":-10,"Mccree":-10,"Mei":10,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":-10,"Reaper":-10,"Reinhardt":10,"Roadhog":-10,"Sigma":-10,"Soldier: 76":10,"Sombra":-10,"Symmetra":-10,"Torbjörn":10,"Tracer":-10,"Widowmaker":10,"Winston":10,"Wrecking Ball":10,"Zarya":-10,"Zenyatta":-10},
    "Pharah" : {"Ana":-10,"Ashe":-10,"Baptiste":-20,"Bastion":-10,"Brigitte":20,"D.Va":-10,"Doomfist":20,"Genji":10,"Hanzo":0,"Junkrat":20,"Lucio":0,"Mccree":-10,"Mei":10,"Mercy":-10,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":10,"Reinhardt":10,"Roadhog":10,"Sigma":0,"Soldier: 76":-20,"Sombra":-10,"Symmetra":20,"Torbjörn":10,"Tracer":0,"Widowmaker":-20,"Winston":-10,"Wrecking Ball":-10,"Zarya":10,"Zenyatta":0},
    "Reaper" : {"Ana":0,"Ashe":-10,"Baptiste":0,"Bastion":10,"Brigitte":-10,"D.Va":-10,"Doomfist":10,"Genji":0,"Hanzo":-10,"Junkrat":0,"Lucio":0,"Mccree":-10,"Mei":0,"Mercy":0,"Moira":-10,"Orisa":10,"Pharah":-10,"Reaper":0,"Reinhardt":10,"Roadhog":10,"Sigma":-20,"Soldier: 76":-10,"Sombra":10,"Symmetra":0,"Torbjörn":-10,"Tracer":10,"Widowmaker":-10,"Winston":20,"Wrecking Ball":0,"Zarya":-10,"Zenyatta":10},
    "Reinhardt" : {"Ana":0,"Ashe":10,"Baptiste":-10,"Bastion":-20,"Brigitte":10,"D.Va":10,"Doomfist":-10,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":0,"Mei":-20,"Mercy":0,"Moira":-10,"Orisa":-10,"Pharah":-10,"Reaper":-10,"Reinhardt":20,"Roadhog":0,"Sigma":10,"Soldier: 76":-10,"Sombra":-10,"Symmetra":-10,"Torbjörn":10,"Tracer":-10,"Widowmaker":10,"Winston":-10,"Wrecking Ball":-10,"Zarya":10,"Zenyatta":0},
    "Roadhog" : {"Ana":-10,"Ashe":0,"Baptiste":10,"Bastion":10,"Brigitte":-10,"D.Va":-10,"Doomfist":10,"Genji":0,"Hanzo":10,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":-10,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":-10,"Reaper":-10,"Reinhardt":0,"Roadhog":0,"Sigma":-10,"Soldier: 76":10,"Sombra":-10,"Symmetra":0,"Torbjörn":-10,"Tracer":10,"Widowmaker":0,"Winston":10,"Wrecking Ball":20,"Zarya":-10,"Zenyatta":-10},
    "Sigma" : {"Ana":10,"Ashe":10,"Baptiste":-20,"Bastion":10,"Brigitte":10,"D.Va":0,"Doomfist":-20,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":-10,"Mccree":20,"Mei":-10,"Mercy":0,"Moira":-10,"Orisa":10,"Pharah":0,"Reaper":20,"Reinhardt":-10,"Roadhog":10,"Sigma":0,"Soldier: 76":20,"Sombra":-10,"Symmetra":-10,"Torbjörn":0,"Tracer":0,"Widowmaker":10,"Winston":-20,"Wrecking Ball":0,"Zarya":-10,"Zenyatta":-10},
    "Soldier: 76" : {"Ana":0,"Ashe":10,"Baptiste":10,"Bastion":10,"Brigitte":0,"D.Va":-10,"Doomfist":-10,"Genji":0,"Hanzo":-10,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":10,"Mercy":10,"Moira":10,"Orisa":-10,"Pharah":20,"Reaper":10,"Reinhardt":-10,"Roadhog":-10,"Sigma":-20,"Soldier: 76":0,"Sombra":0,"Symmetra":-10,"Torbjörn":10,"Tracer":10,"Widowmaker":0,"Winston":-10,"Wrecking Ball":-20,"Zarya":10,"Zenyatta":-10},
    "Sombra" : {"Ana":10,"Ashe":10,"Baptiste":10,"Bastion":20,"Brigitte":10,"D.Va":10,"Doomfist":20,"Genji":20,"Hanzo":-10,"Junkrat":-10,"Lucio":-10,"Mccree":-10,"Mei":-10,"Mercy":-10,"Moira":-10,"Orisa":10,"Pharah":10,"Reaper":-10,"Reinhardt":10,"Roadhog":10,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":10,"Torbjörn":-10,"Tracer":10,"Widowmaker":0,"Winston":10,"Wrecking Ball":20,"Zarya":10,"Zenyatta":20},
    "Symmetra" : {"Ana":0,"Ashe":-10,"Baptiste":-10,"Bastion":-10,"Brigitte":-10,"D.Va":20,"Doomfist":-10,"Genji":10,"Hanzo":-10,"Junkrat":-10,"Lucio":0,"Mccree":0,"Mei":-10,"Mercy":0,"Moira":-10,"Orisa":10,"Pharah":-20,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":10,"Sombra":-10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":10,"Winston":-20,"Wrecking Ball":10,"Zarya":-10,"Zenyatta":0},
    "Torbjörn" : {"Ana":-10,"Ashe":-10,"Baptiste":-10,"Bastion":10,"Brigitte":10,"D.Va":-10,"Doomfist":0,"Genji":10,"Hanzo":-20,"Junkrat":0,"Lucio":10,"Mccree":-10,"Mei":0,"Mercy":0,"Moira":0,"Orisa":-10,"Pharah":-10,"Reaper":10,"Reinhardt":-10,"Roadhog":10,"Sigma":0,"Soldier: 76":-10,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":-20,"Winston":10,"Wrecking Ball":10,"Zarya":-10,"Zenyatta":-10},
    "Tracer" : {"Ana":10,"Ashe":-10,"Baptiste":-10,"Bastion":10,"Brigitte":-20,"D.Va":-10,"Doomfist":10,"Genji":0,"Hanzo":-10,"Junkrat":-10,"Lucio":-10,"Mccree":-10,"Mei":0,"Mercy":10,"Moira":-10,"Orisa":10,"Pharah":0,"Reaper":-10,"Reinhardt":10,"Roadhog":-10,"Sigma":0,"Soldier: 76":-10,"Sombra":-10,"Symmetra":-10,"Torbjörn":-10,"Tracer":0,"Widowmaker":10,"Winston":0,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "Widowmaker" : {"Ana":10,"Ashe":10,"Baptiste":-10,"Bastion":10,"Brigitte":10,"D.Va":-10,"Doomfist":10,"Genji":-10,"Hanzo":10,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":0,"Mercy":10,"Moira":10,"Orisa":-10,"Pharah":20,"Reaper":10,"Reinhardt":-10,"Roadhog":0,"Sigma":-10,"Soldier: 76":0,"Sombra":0,"Symmetra":-10,"Torbjörn":20,"Tracer":-10,"Widowmaker":10,"Winston":-10,"Wrecking Ball":-10,"Zarya":10,"Zenyatta":10},
    "Winston" : {"Ana":10,"Ashe":10,"Baptiste":0,"Bastion":-20,"Brigitte":-10,"D.Va":-10,"Doomfist":-10,"Genji":10,"Hanzo":10,"Junkrat":0,"Lucio":0,"Mccree":10,"Mei":10,"Mercy":10,"Moira":0,"Orisa":-10,"Pharah":10,"Reaper":-20,"Reinhardt":10,"Roadhog":-10,"Sigma":20,"Soldier: 76":10,"Sombra":-10,"Symmetra":20,"Torbjörn":-10,"Tracer":0,"Widowmaker":10,"Winston":0,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "Wrecking Ball" : {"Ana":-10,"Ashe":10,"Baptiste":10,"Bastion":-10,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":10,"Hanzo":10,"Junkrat":-10,"Lucio":0,"Mccree":-20,"Mei":-20,"Mercy":0,"Moira":0,"Orisa":-10,"Pharah":10,"Reaper":0,"Reinhardt":10,"Roadhog":-20,"Sigma":0,"Soldier: 76":20,"Sombra":-20,"Symmetra":-10,"Torbjörn":-10,"Tracer":0,"Widowmaker":10,"Winston":0,"Wrecking Ball":0,"Zarya":-10,"Zenyatta":-10},
    "Zarya" : {"Ana":0,"Ashe":10,"Baptiste":-10,"Bastion":-10,"Brigitte":10,"D.Va":20,"Doomfist":0,"Genji":10,"Hanzo":0,"Junkrat":20,"Lucio":0,"Mccree":20,"Mei":0,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":-10,"Reaper":10,"Reinhardt":-10,"Roadhog":10,"Sigma":10,"Soldier: 76":-10,"Sombra":-10,"Symmetra":10,"Torbjörn":10,"Tracer":0,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":-10},
    "Zenyatta" : {"Ana":-10,"Ashe":0,"Baptiste":0,"Bastion":10,"Brigitte":0,"D.Va":-10,"Doomfist":-10,"Genji":-10,"Hanzo":10,"Junkrat":10,"Lucio":0,"Mccree":0,"Mei":10,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":-10,"Reinhardt":0,"Roadhog":10,"Sigma":10,"Soldier: 76":10,"Sombra":-20,"Symmetra":0,"Torbjörn":10,"Tracer":-10,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":0}
}

var synergies = {
    "Ana" : {"Ana":0,"Ashe":-10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":10,"Hanzo":-10,"Junkrat":0,"Lucio":10,"Mccree":10,"Mei":0,"Mercy":0,"Moira":-10,"Orisa":0,"Pharah":0,"Reaper":10,"Reinhardt":10,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":0,"Symmetra":10,"Torbjörn":0,"Tracer":0,"Widowmaker":-10,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":0},
    "Ashe" : {"Ana":-10,"Ashe":0,"Baptiste":10,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":10,"Hanzo":10,"Junkrat":0,"Lucio":0,"Mccree":0,"Mei":0,"Mercy":10,"Moira":-10,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":-10,"Winston":10,"Wrecking Ball":10,"Zarya":0,"Zenyatta":10},
    "Baptiste" : {"Ana":0,"Ashe":10,"Baptiste":0,"Bastion":10,"Brigitte":0,"D.Va":10,"Doomfist":0,"Genji":0,"Hanzo":10,"Junkrat":0,"Lucio":0,"Mccree":10,"Mei":0,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":-10,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":0,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":10,"Winston":0,"Wrecking Ball":0,"Zarya":0,"Zenyatta":0},
    "Bastion" : {"Ana":0,"Ashe":0,"Baptiste":10,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":0,"Mei":10,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":10,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":0,"Wrecking Ball":0,"Zarya":0,"Zenyatta":0},
    "Brigitte" : {"Ana":0,"Ashe":0,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":10,"Mei":0,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":0,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":0,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":0,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "D.Va" : {"Ana":0,"Ashe":10,"Baptiste":10,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":10,"Hanzo":0,"Junkrat":10,"Lucio":0,"Mccree":0,"Mei":10,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":10,"Reaper":10,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":10,"Torbjörn":0,"Tracer":10,"Widowmaker":0,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":10},
    "Doomfist" : {"Ana":0,"Ashe":10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":10,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":0,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":10,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":10},
    "Genji" : {"Ana":10,"Ashe":10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":0,"Mercy":10,"Moira":0,"Orisa":0,"Pharah":10,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":0,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":10},
    "Hanzo" : {"Ana":-10,"Ashe":10,"Baptiste":10,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":0,"Mei":0,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":10,"Winston":0,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "Junkrat" : {"Ana":0,"Ashe":0,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":0,"Mei":0,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":10,"Winston":0,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "Lucio" : {"Ana":10,"Ashe":0,"Baptiste":0,"Bastion":0,"Brigitte":10,"D.Va":0,"Doomfist":10,"Genji":10,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":10,"Mei":10,"Mercy":0,"Moira":10,"Orisa":0,"Pharah":-10,"Reaper":10,"Reinhardt":10,"Roadhog":10,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":10,"Torbjörn":10,"Tracer":0,"Widowmaker":-10,"Winston":10,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "Mccree" : {"Ana":10,"Ashe":0,"Baptiste":10,"Bastion":0,"Brigitte":10,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":10,"Mercy":10,"Moira":0,"Orisa":0,"Pharah":0,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":10,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":0,"Wrecking Ball":10,"Zarya":0,"Zenyatta":0},
    "Mei" : {"Ana":0,"Ashe":0,"Baptiste":0,"Bastion":10,"Brigitte":0,"D.Va":10,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":10,"Mei":0,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":10,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":0,"Wrecking Ball":10,"Zarya":10,"Zenyatta":0},
    "Mercy" : {"Ana":0,"Ashe":10,"Baptiste":10,"Bastion":10,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":10,"Hanzo":10,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":0,"Mercy":0,"Moira":-10,"Orisa":0,"Pharah":10,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":0,"Symmetra":10,"Torbjörn":0,"Tracer":0,"Widowmaker":10,"Winston":10,"Wrecking Ball":0,"Zarya":0,"Zenyatta":10},
    "Moira" : {"Ana":-10,"Ashe":-10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":0,"Mercy":-10,"Moira":0,"Orisa":0,"Pharah":-10,"Reaper":0,"Reinhardt":10,"Roadhog":10,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":-10,"Winston":-10,"Wrecking Ball":0,"Zarya":10,"Zenyatta":-10},
    "Orisa" : {"Ana":0,"Ashe":10,"Baptiste":10,"Bastion":10,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":0,"Hanzo":10,"Junkrat":10,"Lucio":0,"Mccree":0,"Mei":10,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":0,"Reaper":0,"Reinhardt":-10,"Roadhog":10,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":10,"Torbjörn":10,"Tracer":10,"Widowmaker":10,"Winston":-10,"Wrecking Ball":10,"Zarya":-10,"Zenyatta":10},
    "Pharah" : {"Ana":0,"Ashe":0,"Baptiste":-10,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":0,"Genji":10,"Hanzo":0,"Junkrat":0,"Lucio":-10,"Mccree":0,"Mei":0,"Mercy":10,"Moira":-10,"Orisa":0,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":0,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":10},
    "Reaper" : {"Ana":10,"Ashe":0,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":10,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":10,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "Reinhardt" : {"Ana":10,"Ashe":10,"Baptiste":0,"Bastion":10,"Brigitte":10,"D.Va":10,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":10,"Mei":10,"Mercy":0,"Moira":10,"Orisa":-10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":10,"Symmetra":10,"Torbjörn":10,"Tracer":0,"Widowmaker":0,"Winston":-10,"Wrecking Ball":0,"Zarya":10,"Zenyatta":0},
    "Roadhog" : {"Ana":0,"Ashe":0,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":0,"Mercy":0,"Moira":10,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":0,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":-10,"Wrecking Ball":0,"Zarya":0,"Zenyatta":0},
    "Sigma" : {"Ana":0,"Ashe":0,"Baptiste":0,"Bastion":10,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":0,"Hanzo":10,"Junkrat":10,"Lucio":10,"Mccree":10,"Mei":10,"Mercy":0,"Moira":10,"Orisa":-10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":0,"Symmetra":10,"Torbjörn":0,"Tracer":0,"Widowmaker":10,"Winston":10,"Wrecking Ball":0,"Zarya":10,"Zenyatta":0},
    "Soldier: 76" : {"Ana":10,"Ashe":0,"Baptiste":10,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":0,"Mei":0,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":10,"Wrecking Ball":10,"Zarya":0,"Zenyatta":10},
    "Sombra" : {"Ana":0,"Ashe":10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":10,"Hanzo":0,"Junkrat":10,"Lucio":0,"Mccree":10,"Mei":10,"Mercy":0,"Moira":0,"Orisa":0,"Pharah":10,"Reaper":10,"Reinhardt":10,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":0,"Symmetra":0,"Torbjörn":10,"Tracer":10,"Widowmaker":0,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":0},
    "Symmetra" : {"Ana":10,"Ashe":0,"Baptiste":0,"Bastion":10,"Brigitte":0,"D.Va":10,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":10,"Mei":0,"Mercy":10,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":0,"Torbjörn":10,"Tracer":0,"Widowmaker":0,"Winston":0,"Wrecking Ball":0,"Zarya":0,"Zenyatta":10},
    "Torbjörn" : {"Ana":0,"Ashe":0,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":0,"Genji":0,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":0,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":10,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":10,"Symmetra":10,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":0,"Wrecking Ball":0,"Zarya":10,"Zenyatta":0},
    "Tracer" : {"Ana":0,"Ashe":10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":10,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":0,"Mei":0,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":10,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":10},
    "Widowmaker" : {"Ana":-10,"Ashe":-10,"Baptiste":10,"Bastion":0,"Brigitte":0,"D.Va":0,"Doomfist":10,"Genji":0,"Hanzo":10,"Junkrat":10,"Lucio":-10,"Mccree":0,"Mei":0,"Mercy":10,"Moira":-10,"Orisa":10,"Pharah":0,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":0,"Symmetra":0,"Torbjörn":0,"Tracer":0,"Widowmaker":0,"Winston":0,"Wrecking Ball":10,"Zarya":0,"Zenyatta":10},
    "Winston" : {"Ana":10,"Ashe":10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":10,"Hanzo":0,"Junkrat":0,"Lucio":10,"Mccree":0,"Mei":0,"Mercy":10,"Moira":-10,"Orisa":-10,"Pharah":10,"Reaper":10,"Reinhardt":-10,"Roadhog":-10,"Sigma":10,"Soldier: 76":10,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":0,"Winston":0,"Wrecking Ball":10,"Zarya":10,"Zenyatta":10},
    "Wrecking Ball" : {"Ana":10,"Ashe":10,"Baptiste":0,"Bastion":0,"Brigitte":0,"D.Va":10,"Doomfist":10,"Genji":10,"Hanzo":0,"Junkrat":0,"Lucio":0,"Mccree":10,"Mei":10,"Mercy":0,"Moira":0,"Orisa":10,"Pharah":10,"Reaper":0,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":10,"Symmetra":0,"Torbjörn":0,"Tracer":10,"Widowmaker":10,"Winston":10,"Wrecking Ball":0,"Zarya":10,"Zenyatta":10},
    "Zarya" : {"Ana":10,"Ashe":0,"Baptiste":0,"Bastion":0,"Brigitte":10,"D.Va":10,"Doomfist":10,"Genji":10,"Hanzo":10,"Junkrat":10,"Lucio":10,"Mccree":0,"Mei":10,"Mercy":0,"Moira":10,"Orisa":-10,"Pharah":10,"Reaper":10,"Reinhardt":10,"Roadhog":0,"Sigma":10,"Soldier: 76":0,"Sombra":10,"Symmetra":0,"Torbjörn":10,"Tracer":10,"Widowmaker":0,"Winston":10,"Wrecking Ball":10,"Zarya":0,"Zenyatta":10},
    "Zenyatta" : {"Ana":0,"Ashe":10,"Baptiste":0,"Bastion":0,"Brigitte":10,"D.Va":10,"Doomfist":10,"Genji":10,"Hanzo":10,"Junkrat":10,"Lucio":10,"Mccree":0,"Mei":0,"Mercy":10,"Moira":-10,"Orisa":10,"Pharah":10,"Reaper":10,"Reinhardt":0,"Roadhog":0,"Sigma":0,"Soldier: 76":10,"Sombra":0,"Symmetra":10,"Torbjörn":0,"Tracer":10,"Widowmaker":10,"Winston":10,"Wrecking Ball":10,"Zarya":10,"Zenyatta":0},
}

var defaultOptions = {
    tier : "MetaBomb"
}